version: '3.0'
services:
  service:
    build:
      context: ./service
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./service/src:/app/src
    ports:
      - "127.0.0.1:80:80"
    env_file:
      - ./service/variables.env
  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./ui:/app
    ports:
      - "127.0.0.1:3000:3000"
  postgres:
    image: postgres:15.2-alpine3.17
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    volumes:
      - ./postgresql/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    ports:
      - "5432:5432"
  pgadmin-compose:
    image: dpage/pgadmin4
    ports:
      - "16543:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "abc@mail.com"
      PGADMIN_DEFAULT_PASSWORD: "123456"
    depends_on:
      - postgres